apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: local-explainer-video
spec:
  entrypoint: pipeline

  templates:
  - name: pipeline
    steps:
    - - name: generate-script
        template: script-generator
    - - name: text-to-speech
        template: tts
        arguments:
          artifacts:
          - name: script
            from: "{{steps.generate-script.outputs.artifacts.script}}"
    - - name: assemble-video
        template: assemble
        arguments:
          artifacts:
          - name: audio
            from: "{{steps.text-to-speech.outputs.artifacts.audio}}"

  - name: script-generator
    container:
      image: localvideo/script-generator:latest
      command: ["python3", "run.py"]
    outputs:
      artifacts:
      - name: script
        path: /output/script.txt

  - name: tts
    container:
      image: localvideo/tts:latest
      command: ["python3", "run.py"]
    inputs:
      artifacts:
      - name: script
        path: /input/script.txt
    outputs:
      artifacts:
      - name: audio
        path: /output/audio.mp3

  - name: assemble
    container:
      image: localvideo/video-assembler:latest
      command: ["python3", "build_video.py"]
    inputs:
      artifacts:
      - name: audio
        path: /input/audio.mp3
    outputs:
      artifacts:
      - name: final_video
        path: /output/final.mp4
