apiVersion: v1
kind: PersistentVolume
metadata:
  name: video-hub-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/video-hub   # Make sure this exists on all nodes
