apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: video-hub
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/<YOUR_USERNAME>/video-hub.git'
    targetRevision: HEAD
    path: charts/video-hub
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
